name: FactionPlugin
version: 1.0-SNAPSHOT
main: fr.jules.faction.FactionPlugin
api-version: 1.20
commands:
  tpa:
    description: Envoyer une demande de téléportation.
  tpahere:
    description: Envoyer une demande pour qu'un joueur se téléporte à vous.
  tpyes:
    description: Accepter une demande de téléportation.
  tpno:
    description: Refuser une demande de téléportation.
  sethome:
    description: Définir une résidence.
  home:
    description: Se rendre à une résidence.
  spawn:
    description: Se rendre au spawn.
  chateau:
    description: Se rendre au château.
  forteresse:
    description: Se rendre à la forteresse.
  f:
    description: Commande principale des factions.
    aliases: [faction]
  money:
    description: Voir son argent.
  power:
    description: Voir son power ou celui d'un autre.
  ignore:
    description: Ignorer un joueur.
  shop:
    description: Ouvrir la boutique du Faction.
  boutique:
    description: Ouvrir la boutique Me's.
