# Configuration du Module Chat
join:
  welcome-first: "§6§lBIENVENUE ! §e%player% §fvient de rejoindre le serveur pour la première fois ! (§6#%count%§f)"
  join-message: "§7[§a+§7] §f%player% a rejoint le combat."
  quit-message: "§7[§c-§7] §f%player% a quitté le combat."

death:
  stupid:
    - "§e%player% §fs'est pris les pieds dans le tapis (chute)."
    - "§e%player% §fa voulu nager dans la lave."
    - "§e%player% §fa oublié de respirer dans l'eau."
    - "§e%player% §fs'est étouffé dans un mur."
  accidental:
    - "§e%player% §fa été foudroyé par le destin."
    - "§e%player% §fne savait pas que ça explosait."
    - "§e%player% §fa été piétiné par un lama en colère."
  combat:
    - "§e%player% §fa été terrassé par §c%killer%§f."
    - "§c%killer% §fa mis fin au règne de §e%player%§f."
    - "§e%player% §fn'a pas fait le poids face à §c%killer%§f."
  other:
    - "§e%player% §fest mort de façon mystérieuse."

pet-death: "§cLe compagnon §e%name% §ca rendu l'âme ! (§7Propriétaire: §f%player%§7)"
